#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

rotate() {
  degree="$1"
  mimetype= "$(file -b -i "$file")"
  case "$mimetype" in
    image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
    *)           mogrify  -rotate "$degree" "$file" ;;
  esac
}

while read file;
do
  case "$1" in
    "C-x")      xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
    "C-c")      while read file; do xclip -selection clipboard -target image/png "$file"; done ;;
    "e") gnome-terminal -- bash -c "exiftool '$file' | less" & ;;
    "s") convert "$file" -gravity Center -resize 1921  "$file.small.jpg" ;;
    "g") setsid -f gimp "$file" & ;;
    "d") setsid -f darktable "$file" & ;;
    "R") rotate 270 ;;
    "r") rotate  90 ;;
  esac
done


